#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_Assault_LlamaRoaster_Athena

#include "Basic.hpp"

#include "B_Assault_LlamaRoaster_Athena_classes.hpp"
#include "B_Assault_LlamaRoaster_Athena_parameters.hpp"


namespace SDK
{

// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.ExecuteUbergraph_B_Assault_LlamaRoaster_Athena
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::ExecuteUbergraph_B_Assault_LlamaRoaster_Athena(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "ExecuteUbergraph_B_Assault_LlamaRoaster_Athena");

	Params::B_Assault_LlamaRoaster_Athena_C_ExecuteUbergraph_B_Assault_LlamaRoaster_Athena Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.SetOverheatParam
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   OverheatParamValue                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::SetOverheatParam(float OverheatParamValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "SetOverheatParam");

	Params::B_Assault_LlamaRoaster_Athena_C_SetOverheatParam Parms{};

	Parms.OverheatParamValue = OverheatParamValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnWeaponAttached
// (Event, Public, BlueprintEvent)

void AB_Assault_LlamaRoaster_Athena_C::OnWeaponAttached()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnWeaponAttached");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnStartCharge
// (Event, Protected, BlueprintEvent)

void AB_Assault_LlamaRoaster_Athena_C::OnStartCharge()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnStartCharge");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.PlayChargeupMontage
// (BlueprintCallable, BlueprintEvent)

void AB_Assault_LlamaRoaster_Athena_C::PlayChargeupMontage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "PlayChargeupMontage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnPlayWeaponFireFX
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bPersistentFire                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bSecondaryFire                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AB_Assault_LlamaRoaster_Athena_C::OnPlayWeaponFireFX(bool bPersistentFire, bool bSecondaryFire)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnPlayWeaponFireFX");

	Params::B_Assault_LlamaRoaster_Athena_C_OnPlayWeaponFireFX Parms{};

	Parms.bPersistentFire = bPersistentFire;
	Parms.bSecondaryFire = bSecondaryFire;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.PlayStartFiringMontage
// (BlueprintCallable, BlueprintEvent)

void AB_Assault_LlamaRoaster_Athena_C::PlayStartFiringMontage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "PlayStartFiringMontage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.PlayFinishedFiringMontage
// (BlueprintCallable, BlueprintEvent)

void AB_Assault_LlamaRoaster_Athena_C::PlayFinishedFiringMontage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "PlayFinishedFiringMontage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnStartHeating
// (Event, Protected, BlueprintEvent)

void AB_Assault_LlamaRoaster_Athena_C::OnStartHeating()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnStartHeating");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnPlayImpactFX
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FHitResult&                HitResult                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// EPhysicalSurface                        ImpactPhysicalSurface                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UFXSystemComponent*               SpawnedPSC                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnPlayImpactFX(const struct FHitResult& HitResult, EPhysicalSurface ImpactPhysicalSurface, class UFXSystemComponent* SpawnedPSC)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnPlayImpactFX");

	Params::B_Assault_LlamaRoaster_Athena_C_OnPlayImpactFX Parms{};

	Parms.HitResult = std::move(HitResult);
	Parms.ImpactPhysicalSurface = ImpactPhysicalSurface;
	Parms.SpawnedPSC = SpawnedPSC;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnOverheatValueChanged_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   CurrentValue                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   MaxValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFortWeaponOverheatState                State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsInCooldown                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AB_Assault_LlamaRoaster_Athena_C::OnOverheatValueChanged_Event_0(float CurrentValue, float MaxValue, EFortWeaponOverheatState State, bool bIsInCooldown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnOverheatValueChanged_Event_0");

	Params::B_Assault_LlamaRoaster_Athena_C_OnOverheatValueChanged_Event_0 Parms{};

	Parms.CurrentValue = CurrentValue;
	Parms.MaxValue = MaxValue;
	Parms.State = State;
	Parms.bIsInCooldown = bIsInCooldown;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "ReceiveTick");

	Params::B_Assault_LlamaRoaster_Athena_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnStartCooling
// (Event, Protected, BlueprintEvent)

void AB_Assault_LlamaRoaster_Athena_C::OnStartCooling()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnStartCooling");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnFinishedCooling
// (Event, Protected, BlueprintEvent)

void AB_Assault_LlamaRoaster_Athena_C::OnFinishedCooling()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnFinishedCooling");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnStopWeaponFireFX
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)

void AB_Assault_LlamaRoaster_Athena_C::OnStopWeaponFireFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnStopWeaponFireFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.Apply Cam Deltas
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   RecoilRaw                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::Apply_Cam_Deltas(const struct FVector& RecoilRaw)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "Apply Cam Deltas");

	Params::B_Assault_LlamaRoaster_Athena_C_Apply_Cam_Deltas Parms{};

	Parms.RecoilRaw = std::move(RecoilRaw);

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.UpdateRecoil
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   RecoilAlpha                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::UpdateRecoil(float RecoilAlpha)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "UpdateRecoil");

	Params::B_Assault_LlamaRoaster_Athena_C_UpdateRecoil Parms{};

	Parms.RecoilAlpha = RecoilAlpha;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnStartOverheated
// (Event, Protected, BlueprintEvent)

void AB_Assault_LlamaRoaster_Athena_C::OnStartOverheated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnStartOverheated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.CustomEvent_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortWeapon*                      Weapon                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::CustomEvent_0(class AFortWeapon* Weapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "CustomEvent_0");

	Params::B_Assault_LlamaRoaster_Athena_C_CustomEvent_0 Parms{};

	Parms.Weapon = Weapon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.TriggerDown
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortWeapon*                      Weapon                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::TriggerDown(class AFortWeapon* Weapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "TriggerDown");

	Params::B_Assault_LlamaRoaster_Athena_C_TriggerDown Parms{};

	Parms.Weapon = Weapon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnCompleted_1471B9C640E1AA0B098754B9AD6438F6
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnCompleted_1471B9C640E1AA0B098754B9AD6438F6(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnCompleted_1471B9C640E1AA0B098754B9AD6438F6");

	Params::B_Assault_LlamaRoaster_Athena_C_OnCompleted_1471B9C640E1AA0B098754B9AD6438F6 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnBlendOut_1471B9C640E1AA0B098754B9AD6438F6
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnBlendOut_1471B9C640E1AA0B098754B9AD6438F6(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnBlendOut_1471B9C640E1AA0B098754B9AD6438F6");

	Params::B_Assault_LlamaRoaster_Athena_C_OnBlendOut_1471B9C640E1AA0B098754B9AD6438F6 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnInterrupted_1471B9C640E1AA0B098754B9AD6438F6
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnInterrupted_1471B9C640E1AA0B098754B9AD6438F6(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnInterrupted_1471B9C640E1AA0B098754B9AD6438F6");

	Params::B_Assault_LlamaRoaster_Athena_C_OnInterrupted_1471B9C640E1AA0B098754B9AD6438F6 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnNotifyBegin_1471B9C640E1AA0B098754B9AD6438F6
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnNotifyBegin_1471B9C640E1AA0B098754B9AD6438F6(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnNotifyBegin_1471B9C640E1AA0B098754B9AD6438F6");

	Params::B_Assault_LlamaRoaster_Athena_C_OnNotifyBegin_1471B9C640E1AA0B098754B9AD6438F6 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnNotifyEnd_1471B9C640E1AA0B098754B9AD6438F6
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnNotifyEnd_1471B9C640E1AA0B098754B9AD6438F6(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnNotifyEnd_1471B9C640E1AA0B098754B9AD6438F6");

	Params::B_Assault_LlamaRoaster_Athena_C_OnNotifyEnd_1471B9C640E1AA0B098754B9AD6438F6 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnCompleted_2C3CBDAC4FB573571577D9BA5421AE52
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnCompleted_2C3CBDAC4FB573571577D9BA5421AE52(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnCompleted_2C3CBDAC4FB573571577D9BA5421AE52");

	Params::B_Assault_LlamaRoaster_Athena_C_OnCompleted_2C3CBDAC4FB573571577D9BA5421AE52 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnBlendOut_2C3CBDAC4FB573571577D9BA5421AE52
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnBlendOut_2C3CBDAC4FB573571577D9BA5421AE52(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnBlendOut_2C3CBDAC4FB573571577D9BA5421AE52");

	Params::B_Assault_LlamaRoaster_Athena_C_OnBlendOut_2C3CBDAC4FB573571577D9BA5421AE52 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnInterrupted_2C3CBDAC4FB573571577D9BA5421AE52
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnInterrupted_2C3CBDAC4FB573571577D9BA5421AE52(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnInterrupted_2C3CBDAC4FB573571577D9BA5421AE52");

	Params::B_Assault_LlamaRoaster_Athena_C_OnInterrupted_2C3CBDAC4FB573571577D9BA5421AE52 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnNotifyBegin_2C3CBDAC4FB573571577D9BA5421AE52
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnNotifyBegin_2C3CBDAC4FB573571577D9BA5421AE52(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnNotifyBegin_2C3CBDAC4FB573571577D9BA5421AE52");

	Params::B_Assault_LlamaRoaster_Athena_C_OnNotifyBegin_2C3CBDAC4FB573571577D9BA5421AE52 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnNotifyEnd_2C3CBDAC4FB573571577D9BA5421AE52
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnNotifyEnd_2C3CBDAC4FB573571577D9BA5421AE52(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnNotifyEnd_2C3CBDAC4FB573571577D9BA5421AE52");

	Params::B_Assault_LlamaRoaster_Athena_C_OnNotifyEnd_2C3CBDAC4FB573571577D9BA5421AE52 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnCompleted_BB649A224020969A85BD01A5F23E6B4A
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnCompleted_BB649A224020969A85BD01A5F23E6B4A(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnCompleted_BB649A224020969A85BD01A5F23E6B4A");

	Params::B_Assault_LlamaRoaster_Athena_C_OnCompleted_BB649A224020969A85BD01A5F23E6B4A Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnBlendOut_BB649A224020969A85BD01A5F23E6B4A
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnBlendOut_BB649A224020969A85BD01A5F23E6B4A(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnBlendOut_BB649A224020969A85BD01A5F23E6B4A");

	Params::B_Assault_LlamaRoaster_Athena_C_OnBlendOut_BB649A224020969A85BD01A5F23E6B4A Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnInterrupted_BB649A224020969A85BD01A5F23E6B4A
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnInterrupted_BB649A224020969A85BD01A5F23E6B4A(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnInterrupted_BB649A224020969A85BD01A5F23E6B4A");

	Params::B_Assault_LlamaRoaster_Athena_C_OnInterrupted_BB649A224020969A85BD01A5F23E6B4A Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnNotifyBegin_BB649A224020969A85BD01A5F23E6B4A
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnNotifyBegin_BB649A224020969A85BD01A5F23E6B4A(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnNotifyBegin_BB649A224020969A85BD01A5F23E6B4A");

	Params::B_Assault_LlamaRoaster_Athena_C_OnNotifyBegin_BB649A224020969A85BD01A5F23E6B4A Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnNotifyEnd_BB649A224020969A85BD01A5F23E6B4A
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnNotifyEnd_BB649A224020969A85BD01A5F23E6B4A(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnNotifyEnd_BB649A224020969A85BD01A5F23E6B4A");

	Params::B_Assault_LlamaRoaster_Athena_C_OnNotifyEnd_BB649A224020969A85BD01A5F23E6B4A Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnCompleted_6E7D44A54F7168F1B2016ABE4CA8589F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnCompleted_6E7D44A54F7168F1B2016ABE4CA8589F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnCompleted_6E7D44A54F7168F1B2016ABE4CA8589F");

	Params::B_Assault_LlamaRoaster_Athena_C_OnCompleted_6E7D44A54F7168F1B2016ABE4CA8589F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnBlendOut_6E7D44A54F7168F1B2016ABE4CA8589F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnBlendOut_6E7D44A54F7168F1B2016ABE4CA8589F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnBlendOut_6E7D44A54F7168F1B2016ABE4CA8589F");

	Params::B_Assault_LlamaRoaster_Athena_C_OnBlendOut_6E7D44A54F7168F1B2016ABE4CA8589F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnInterrupted_6E7D44A54F7168F1B2016ABE4CA8589F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnInterrupted_6E7D44A54F7168F1B2016ABE4CA8589F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnInterrupted_6E7D44A54F7168F1B2016ABE4CA8589F");

	Params::B_Assault_LlamaRoaster_Athena_C_OnInterrupted_6E7D44A54F7168F1B2016ABE4CA8589F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnNotifyBegin_6E7D44A54F7168F1B2016ABE4CA8589F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnNotifyBegin_6E7D44A54F7168F1B2016ABE4CA8589F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnNotifyBegin_6E7D44A54F7168F1B2016ABE4CA8589F");

	Params::B_Assault_LlamaRoaster_Athena_C_OnNotifyBegin_6E7D44A54F7168F1B2016ABE4CA8589F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnNotifyEnd_6E7D44A54F7168F1B2016ABE4CA8589F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnNotifyEnd_6E7D44A54F7168F1B2016ABE4CA8589F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnNotifyEnd_6E7D44A54F7168F1B2016ABE4CA8589F");

	Params::B_Assault_LlamaRoaster_Athena_C_OnNotifyEnd_6E7D44A54F7168F1B2016ABE4CA8589F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnCompleted_7451062C436093CBBE2AF3980E8F7950
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnCompleted_7451062C436093CBBE2AF3980E8F7950(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnCompleted_7451062C436093CBBE2AF3980E8F7950");

	Params::B_Assault_LlamaRoaster_Athena_C_OnCompleted_7451062C436093CBBE2AF3980E8F7950 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnBlendOut_7451062C436093CBBE2AF3980E8F7950
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnBlendOut_7451062C436093CBBE2AF3980E8F7950(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnBlendOut_7451062C436093CBBE2AF3980E8F7950");

	Params::B_Assault_LlamaRoaster_Athena_C_OnBlendOut_7451062C436093CBBE2AF3980E8F7950 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnInterrupted_7451062C436093CBBE2AF3980E8F7950
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnInterrupted_7451062C436093CBBE2AF3980E8F7950(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnInterrupted_7451062C436093CBBE2AF3980E8F7950");

	Params::B_Assault_LlamaRoaster_Athena_C_OnInterrupted_7451062C436093CBBE2AF3980E8F7950 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnNotifyBegin_7451062C436093CBBE2AF3980E8F7950
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnNotifyBegin_7451062C436093CBBE2AF3980E8F7950(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnNotifyBegin_7451062C436093CBBE2AF3980E8F7950");

	Params::B_Assault_LlamaRoaster_Athena_C_OnNotifyBegin_7451062C436093CBBE2AF3980E8F7950 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnNotifyEnd_7451062C436093CBBE2AF3980E8F7950
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnNotifyEnd_7451062C436093CBBE2AF3980E8F7950(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnNotifyEnd_7451062C436093CBBE2AF3980E8F7950");

	Params::B_Assault_LlamaRoaster_Athena_C_OnNotifyEnd_7451062C436093CBBE2AF3980E8F7950 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnCompleted_2EE5A63F4B69BA44C3316CB357391388
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnCompleted_2EE5A63F4B69BA44C3316CB357391388(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnCompleted_2EE5A63F4B69BA44C3316CB357391388");

	Params::B_Assault_LlamaRoaster_Athena_C_OnCompleted_2EE5A63F4B69BA44C3316CB357391388 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnBlendOut_2EE5A63F4B69BA44C3316CB357391388
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnBlendOut_2EE5A63F4B69BA44C3316CB357391388(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnBlendOut_2EE5A63F4B69BA44C3316CB357391388");

	Params::B_Assault_LlamaRoaster_Athena_C_OnBlendOut_2EE5A63F4B69BA44C3316CB357391388 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnInterrupted_2EE5A63F4B69BA44C3316CB357391388
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnInterrupted_2EE5A63F4B69BA44C3316CB357391388(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnInterrupted_2EE5A63F4B69BA44C3316CB357391388");

	Params::B_Assault_LlamaRoaster_Athena_C_OnInterrupted_2EE5A63F4B69BA44C3316CB357391388 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnNotifyBegin_2EE5A63F4B69BA44C3316CB357391388
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnNotifyBegin_2EE5A63F4B69BA44C3316CB357391388(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnNotifyBegin_2EE5A63F4B69BA44C3316CB357391388");

	Params::B_Assault_LlamaRoaster_Athena_C_OnNotifyBegin_2EE5A63F4B69BA44C3316CB357391388 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.OnNotifyEnd_2EE5A63F4B69BA44C3316CB357391388
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_LlamaRoaster_Athena_C::OnNotifyEnd_2EE5A63F4B69BA44C3316CB357391388(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "OnNotifyEnd_2EE5A63F4B69BA44C3316CB357391388");

	Params::B_Assault_LlamaRoaster_Athena_C_OnNotifyEnd_2EE5A63F4B69BA44C3316CB357391388 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.AlphaFade__UpdateFunc
// (BlueprintEvent)

void AB_Assault_LlamaRoaster_Athena_C::AlphaFade__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "AlphaFade__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_LlamaRoaster_Athena.B_Assault_LlamaRoaster_Athena_C.AlphaFade__FinishedFunc
// (BlueprintEvent)

void AB_Assault_LlamaRoaster_Athena_C::AlphaFade__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_LlamaRoaster_Athena_C", "AlphaFade__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

