#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BodyguardUI

#include "Basic.hpp"

#include "BodyguardRuntime_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// Class BodyguardUI.BodyguardWidgetBase
// 0x0010 (0x0330 - 0x0320)
class UBodyguardWidgetBase : public ULTMWidgetBase
{
public:
	class AFortAthenaMutator_Bodyguard*           CachedBodyguardMutator;                            // 0x0320(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UAthenaPlayerViewModel*                 CachedPlayerVM;                                    // 0x0328(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void HandleLocalPlayerEliminatedVIP_BP();
	void HandleOnBodyguardIsTooFarFromBodyguard_BP();
	void HandleOnGamePhaseChanged_BP(EAthenaGamePhase NewPhase);
	void HandleOnNotifyVIPTeammateDBNO_BP();
	void HandleOnRevealPlayerRole_BP();
	void HandleOnTeamVIPReassignment_BP(const class AFortPlayerStateAthena* NewVIPPlayerState);
	void HandleOnVIPDataChange();
	void HandlePlayerRoleChange_BP(const EBodyguardPlayerRole NewPlayerRole);
	void HandleVIPTookDamage_BP();
	void MutatorReady();
	void OnMutatorAvailable(class AFortGameplayMutator* MutatorActor);
	void UpdateEnemyVIPCount_BP(const uint8 EnemyVIPCount);

	class AFortAthenaMutator_Bodyguard* GetBodyguardMutator() const;
	EBodyguardPlayerRole GetOwningPlayerRole() const;
	class AFortPlayerState* GetVIPPlayerStateForTeam(uint8 TeamNum) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"BodyguardWidgetBase">();
	}
	static class UBodyguardWidgetBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBodyguardWidgetBase>();
	}
};

// Class BodyguardUI.BodyguardPlayerInfoBase
// 0x0010 (0x0340 - 0x0330)
class UBodyguardPlayerInfoBase final : public UBodyguardWidgetBase
{
public:
	uint8                                         Pad_330[0x10];                                     // 0x0330(0x0010)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	void HandleViewingPlayerStateChanged();

	bool IsViewingPlayerVIP() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"BodyguardPlayerInfoBase">();
	}
	static class UBodyguardPlayerInfoBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBodyguardPlayerInfoBase>();
	}
};

// Class BodyguardUI.BodyguardPlayerRoleRevealWidget
// 0x0000 (0x0330 - 0x0330)
class UBodyguardPlayerRoleRevealWidget final : public UBodyguardWidgetBase
{
public:
	void SetTeamVIPAvatarImage(uint8 TeamNum, class UFortLazyImage* AvatarImageWidget) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"BodyguardPlayerRoleRevealWidget">();
	}
	static class UBodyguardPlayerRoleRevealWidget* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBodyguardPlayerRoleRevealWidget>();
	}
};

// Class BodyguardUI.BodyguardRumbleHUD
// 0x0000 (0x0330 - 0x0330)
class UBodyguardRumbleHUD final : public UBodyguardWidgetBase
{
public:
	void UpdatedVIPCount_BP(const uint8 EnemyVIPs, const uint8 FriendlyVIPs);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"BodyguardRumbleHUD">();
	}
	static class UBodyguardRumbleHUD* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBodyguardRumbleHUD>();
	}
};

// Class BodyguardUI.BodyguardVIPEliminatedWidget
// 0x0000 (0x0330 - 0x0330)
class UBodyguardVIPEliminatedWidget final : public UBodyguardWidgetBase
{
public:
	void HandleLocalTeamEliminated_BP();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"BodyguardVIPEliminatedWidget">();
	}
	static class UBodyguardVIPEliminatedWidget* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBodyguardVIPEliminatedWidget>();
	}
};

}

