#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_Athena_HidingProp_LandedOn

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Athena_HidingProp_LandedOn.GA_Athena_HidingProp_LandedOn_C
// 0x0030 (0x0AC8 - 0x0A98)
class UGA_Athena_HidingProp_LandedOn_C final : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0A98(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FScalableFloat                         HidingEnabled;                                     // 0x0AA0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_GA_Athena_HidingProp_LandedOn(int32 EntryPoint);
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Athena_HidingProp_LandedOn_C">();
	}
	static class UGA_Athena_HidingProp_LandedOn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_HidingProp_LandedOn_C>();
	}
};

}

