#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_Ranged_PastaRipper_Damage

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Ranged_PastaRipper_Damage.GA_Ranged_PastaRipper_Damage_C
// 0x0010 (0x0AE0 - 0x0AD0)
class UGA_Ranged_PastaRipper_Damage_C final : public UFortGameplayAbility_RangedWeapon
{
public:
	struct FGameplayTag                           GT_EventWeaponFire;                                // 0x0AD0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          ManualFireEvent;                                   // 0x0AD8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void K2_CommitExecute();
	void GetEventData(const struct FGameplayTag& EventTag, struct FGameplayEventData* GameplayEventData);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Ranged_PastaRipper_Damage_C">();
	}
	static class UGA_Ranged_PastaRipper_Damage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Ranged_PastaRipper_Damage_C>();
	}
};

}

