#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GetAllButton

#include "Basic.hpp"

#include "GetAllButton_classes.hpp"
#include "GetAllButton_parameters.hpp"


namespace SDK
{

// Function GetAllButton.GetAllButton_C.ExecuteUbergraph_GetAllButton
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGetAllButton_C::ExecuteUbergraph_GetAllButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GetAllButton_C", "ExecuteUbergraph_GetAllButton");

	Params::GetAllButton_C_ExecuteUbergraph_GetAllButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GetAllButton.GetAllButton_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UGetAllButton_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GetAllButton_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GetAllButton.GetAllButton_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UGetAllButton_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GetAllButton_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GetAllButton.GetAllButton_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UGetAllButton_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GetAllButton_C", "BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GetAllButton.GetAllButton_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UGetAllButton_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GetAllButton_C", "BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GetAllButton.GetAllButton_C.Set Text Data
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Page_Complete_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   Starting_Page                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Ending_Page                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Cost                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGetAllButton_C::Set_Text_Data(bool Page_Complete_0, int32 Starting_Page, int32 Ending_Page, int32 Cost)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GetAllButton_C", "Set Text Data");

	Params::GetAllButton_C_Set_Text_Data Parms{};

	Parms.Page_Complete_0 = Page_Complete_0;
	Parms.Starting_Page = Starting_Page;
	Parms.Ending_Page = Ending_Page;
	Parms.Cost = Cost;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GetAllButton.GetAllButton_C.UpdateTextAndStyle
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECommonInputType                        Input_Type                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGetAllButton_C::UpdateTextAndStyle(ECommonInputType Input_Type)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GetAllButton_C", "UpdateTextAndStyle");

	Params::GetAllButton_C_UpdateTextAndStyle Parms{};

	Parms.Input_Type = Input_Type;

	UObject::ProcessEvent(Func, &Parms);
}

}

