#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: KnobFilterRange_Knob_Device_ShootingTarget_Team

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KnobFilterRange_Knob_Device_ShootingTarget_Team.KnobFilterRange_Knob_Device_ShootingTarget_Team_C
// 0x0000 (0x00C8 - 0x00C8)
class UKnobFilterRange_Knob_Device_ShootingTarget_Team_C final : public UPlaylistUserOptionsFilterRange
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"KnobFilterRange_Knob_Device_ShootingTarget_Team_C">();
	}
	static class UKnobFilterRange_Knob_Device_ShootingTarget_Team_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKnobFilterRange_Knob_Device_ShootingTarget_Team_C>();
	}
};

}

