#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BattlePassTileEmpty

#include "Basic.hpp"

#include "BattlePassBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BattlePassTileEmpty.BattlePassTileEmpty_C
// 0x0000 (0x0CA0 - 0x0CA0)
class UBattlePassTileEmpty_C final : public UFortBattlePassTileBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BattlePassTileEmpty_C">();
	}
	static class UBattlePassTileEmpty_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBattlePassTileEmpty_C>();
	}
};

}

