#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_Block_GravyGoblin

#include "Basic.hpp"

#include "GA_Block_GravyGoblin_classes.hpp"
#include "GA_Block_GravyGoblin_parameters.hpp"


namespace SDK
{

// Function GA_Block_GravyGoblin.GA_Block_GravyGoblin_C.ExecuteUbergraph_GA_Block_GravyGoblin
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Block_GravyGoblin_C::ExecuteUbergraph_GA_Block_GravyGoblin(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Block_GravyGoblin_C", "ExecuteUbergraph_GA_Block_GravyGoblin");

	Params::GA_Block_GravyGoblin_C_ExecuteUbergraph_GA_Block_GravyGoblin Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Block_GravyGoblin.GA_Block_GravyGoblin_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Block_GravyGoblin_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Block_GravyGoblin_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Block_GravyGoblin.GA_Block_GravyGoblin_C.Removed_0A98CD024061A79D0FA31E8AFBC661C4
// (BlueprintCallable, BlueprintEvent)

void UGA_Block_GravyGoblin_C::Removed_0A98CD024061A79D0FA31E8AFBC661C4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Block_GravyGoblin_C", "Removed_0A98CD024061A79D0FA31E8AFBC661C4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Block_GravyGoblin.GA_Block_GravyGoblin_C.Added_35817E954DB467A534E14A9EC6202A63
// (BlueprintCallable, BlueprintEvent)

void UGA_Block_GravyGoblin_C::Added_35817E954DB467A534E14A9EC6202A63()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Block_GravyGoblin_C", "Added_35817E954DB467A534E14A9EC6202A63");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Block_GravyGoblin.GA_Block_GravyGoblin_C.EventReceived_7CBC3A2449FAA2180916D5BFD94B1673
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_Block_GravyGoblin_C::EventReceived_7CBC3A2449FAA2180916D5BFD94B1673(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Block_GravyGoblin_C", "EventReceived_7CBC3A2449FAA2180916D5BFD94B1673");

	Params::GA_Block_GravyGoblin_C_EventReceived_7CBC3A2449FAA2180916D5BFD94B1673 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}

}

