#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCN_ValetMod_OffRoadTire_Destroy

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_ValetMod_OffRoadTire_Destroy.GCN_ValetMod_OffRoadTire_Destroy_C
// 0x0000 (0x01A8 - 0x01A8)
class UGCN_ValetMod_OffRoadTire_Destroy_C final : public UFortGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_ValetMod_OffRoadTire_Destroy_C">();
	}
	static class UGCN_ValetMod_OffRoadTire_Destroy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_ValetMod_OffRoadTire_Destroy_C>();
	}
};

}

