#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCNL_ReviveGrenade_Explosion

#include "Basic.hpp"

#include "GCNL_ReviveGrenade_Explosion_classes.hpp"
#include "GCNL_ReviveGrenade_Explosion_parameters.hpp"


namespace SDK
{

// Function GCNL_ReviveGrenade_Explosion.GCNL_ReviveGrenade_Explosion_C.ExecuteUbergraph_GCNL_ReviveGrenade_Explosion
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AGCNL_ReviveGrenade_Explosion_C::ExecuteUbergraph_GCNL_ReviveGrenade_Explosion(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCNL_ReviveGrenade_Explosion_C", "ExecuteUbergraph_GCNL_ReviveGrenade_Explosion");

	Params::GCNL_ReviveGrenade_Explosion_C_ExecuteUbergraph_GCNL_ReviveGrenade_Explosion Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GCNL_ReviveGrenade_Explosion.GCNL_ReviveGrenade_Explosion_C.K2_HandleGameplayCue
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EGameplayCueEvent                       EventType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayCueParameters&    Parameters                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void AGCNL_ReviveGrenade_Explosion_C::K2_HandleGameplayCue(class AActor* MyTarget, EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCNL_ReviveGrenade_Explosion_C", "K2_HandleGameplayCue");

	Params::GCNL_ReviveGrenade_Explosion_C_K2_HandleGameplayCue Parms{};

	Parms.MyTarget = MyTarget;
	Parms.EventType = EventType;
	Parms.Parameters = std::move(Parameters);

	UObject::ProcessEvent(Func, &Parms);
}

}

